# Use Ubuntu 20.04 as the base image
FROM ubuntu:20.04

# Set non-interactive mode for apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install essential packages
# Install ca-certificates to avoid SSL verification errors
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    wget \
    libboost-all-dev \
    libusb-1.0-0-dev \
    libflann-dev \
    libvtk7-dev \
    libopenni2-dev \
    libpcap-dev \
    libpng-dev \
    libqhull-dev \
    libglew-dev \
    freeglut3-dev \
    pkg-config \
    ca-certificates \
    libsuitesparse-dev \
    libcxsparse3 \
    libgoogle-glog-dev \
    libgflags-dev \
    libatlas-base-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install specific version of Eigen (3.4.0)
RUN wget -q https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz && \
    tar -xzf eigen-3.4.0.tar.gz && \
    cd eigen-3.4.0 && \
    mkdir build && cd build && \
    cmake .. && \
    make install && \
    cd ../../ && rm -rf eigen-3.4.0.tar.gz eigen-3.4.0

# Install Abseil library (needed for Ceres)
RUN git clone --depth 1 https://github.com/abseil/abseil-cpp.git /abseil && \
    cd /abseil && \
    mkdir build && cd build && \
    cmake .. && \
    make -j$(nproc) && \
    make install && \
    ldconfig && \
    cd ../.. && rm -rf /abseil

# Clone the PCL repository
RUN git clone --depth 1 https://github.com/PointCloudLibrary/pcl.git /pcl

# Create a build directory for PCL
WORKDIR /pcl/build

# Build PCL using CMake
RUN cmake .. && \
    make -j$(nproc) && \
    make install && \
    ldconfig && \
    cd ../.. && rm -rf /pcl

# Install Ceres Solver
RUN git clone --depth 1 https://ceres-solver.googlesource.com/ceres-solver /ceres-solver && \
    mkdir /ceres-solver/build && \
    cd /ceres-solver/build && \
    cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DBUILD_CERES_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -Dabsl_VERSION=20210324.0.0 && \
    make -j$(nproc) && \
    make install && \
    ldconfig && \
    cd ../.. && rm -rf /ceres-solver

# Install Fastor
RUN git clone --depth 1 https://github.com/romeric/Fastor.git /opt/Fastor

# Copy the repo (adjust path as necessary)
WORKDIR /opt
COPY ../divergence_free_corr /opt/divergence_free_correspondence
