# Use Ubuntu 20.04 as the base image
FROM ubuntu:20.04

# Set non-interactive mode for apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install essential packages
# Install ca-certificates to avoid SSL verification errors
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    wget \
    libboost-system-dev \
    libboost-filesystem-dev \
    libboost-thread-dev \
    libboost-date-time-dev \
    libboost-iostreams-dev \
    libflann-dev \
    libqhull-dev \
    pkg-config \
    ca-certificates \
    libsuitesparse-dev \
    libcxsparse3 \
    libgoogle-glog-dev \
    libgflags-dev \
    libatlas-base-dev \
    libmetis-dev \
    libpcap-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install specific version of Eigen (3.4.0)
RUN wget -q https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz && \
    tar -xzf eigen-3.4.0.tar.gz && \
    cd eigen-3.4.0 && \
    mkdir build && cd build && \
    cmake .. && \
    make install && \
    cd ../../ && rm -rf eigen-3.4.0.tar.gz eigen-3.4.0

# Clone and build PCL
RUN git clone --depth 1 https://github.com/PointCloudLibrary/pcl.git /pcl && \
    cd /pcl && mkdir build && cd build && \
    cmake .. \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_CXX_STANDARD=20 \
        -DWITH_VTK=OFF \
        -DWITH_QT=OFF \
        -DWITH_OPENGL=OFF \
        -DWITH_PNG=OFF \
        -DWITH_RSSDK=OFF \
        -DBUILD_visualization=OFF \
        -DBUILD_apps=OFF \
        -DBUILD_tools=OFF \
        -DBUILD_examples=OFF \
        -DBUILD_global_tests=OFF \
        && \
    make -j$(nproc) && make install && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local.conf && \
    ldconfig && \
    cd ../../ && rm -rf /pcl

# Install Ceres Solver
RUN wget https://github.com/ceres-solver/ceres-solver/archive/refs/tags/2.2.0.tar.gz && \
    tar -xf 2.2.0.tar.gz && \
    rm 2.2.0.tar.gz && \
    cd ceres-solver-2.2.0 && mkdir build && cd build && cmake .. -DUSE_CUDA:BOOL=OFF &&\
    make -j  && make install && \
    cd ../.. && rm -rf ceres-solver-2.2.0
